name: Main
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "renaissancebench/buildenv:v5-openjdk17"
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix Git safe directory
        shell: bash
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Check file encoding
        shell: bash
        run: tools/ci/check-encoding.sh

      - name: Cache SBT native client
        uses: actions/cache@v3
        with:
          key: sbt_client-${{ runner.os }}-${{ hashFiles('project/build.properties') }}
          path: ~/.cache/sbt/boot/sbtn

      - name: Cache SBT runtime jars
        uses: actions/cache@v3
        with:
          key: sbt_runtime-${{ hashFiles('project/build.properties') }}
          path: .cache/sbt/boot/scala-*

      - name: Cache Coursier cache
        uses: actions/cache@v3
        with:
          key: coursier_cache-${{ hashFiles('build.sbt') }}
          path: .cache/coursier

      - name: Start SBT server
        shell: bash
        run: tools/ci/sbt-server-start.sh

      - name: Check source code formatting
        shell: bash
        run: tools/ci/check-formatting.sh

#      - name: Build both base & JMH bundles
#        shell: bash
#        run: tools/ci/build-both.sh

#      - name: Check generated files are up-to-date
#        shell: bash
#        run: tools/ci/check-markdown.sh

#      - name: Check JMH bundle
#        shell: bash
#        run: tools/ci/check-jmh.sh

      - name: Stop SBT server
        shell: bash
        run: tools/ci/sbt-server-stop.sh

#      - name: Upload base bundle
#        uses: actions/upload-artifact@v3
#        with:

  windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix Git safe directory
        shell: bash
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Fetch JDK 17
        run: |
          aria2c -d ${{ runner.temp }} -o openjdk-17_windows-x64_bin.zip https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_windows-x64_bin.zip

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/openjdk-17_windows-x64_bin.zip

      - name: Environment configuration
        shell: bash
        run: tools/ci/pre-show-env.sh

      - name: Cache SBT native client
        uses: actions/cache@v3
        with:
          key: sbt_client-${{ runner.os }}-${{ hashFiles('project/build.properties') }}
          path: ~/.cache/sbt/boot/sbtn

      - name: Cache SBT runtime jars
        uses: actions/cache@v3
        with:
          key: sbt_runtime-${{ hashFiles('project/build.properties') }}
          enableCrossOsArchive: true
          path: .cache/sbt/boot/scala-*

      - name: Cache Coursier cache
        uses: actions/cache@v3
        with:
          key: coursier_cache-${{ hashFiles('build.sbt') }}
          enableCrossOsArchive: true
          path: .cache/coursier

      - name: Start SBT server
        shell: bash
        run: tools/ci/sbt-server-start.sh
